spring:
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: https://example.org
          predicates:
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
            - Before=2017-01-20T17:42:47.789-07:00[America/Denver]
            - Between=2017-01-20T17:42:47.789-07:00[America/Denver], 2017-01-21T17:42:47.789-07:00[America/Denver]
            # cookie chocolate 的值 满足正则表达式
            - Cookie=chocolate, ch.p
            - Header=X-Request-Id, \d+
            # 请求头 Host 满足
            - Host=**.somehost.org,**.anotherhost.org
            - Method=GET,POST
            - Path=/red/{segment},/blue/{segment}
            # 包含查询参数 red 且其值符合正则表达式
            # - Query=red, gree.
            # 包含查询参数 即可
            - Query=red
            # 如果请求的远程地址是 192.168.1.10 ，则此路由匹配。
            - RemoteAddr=192.168.1.1/24
            # 如果 X-Forwarded-For 标头包含 192.168.1.10 ，则此路由匹配
            - XForwardedRemoteAddr=192.168.1.1/24
        - id: weight_high
          uri: https://weighthigh.org
          predicates:
            - Weight=group1, 8
        - id: weight_low
          uri: https://weightlow.org
          predicates:
            - Weight=group1, 2