spring:
  cloud:
    gateway:
      default-filters:
        # 这是正则分组的语法
        - RewritePath=/index/?(?<segment>.*), /$\{segment}
        - RewritePath=/weight/?(?<segment>.*), /index
        - RouteId
      routes:
        - id: weight_high
          uri: http://localhost:8080
          predicates:
            - Path=/weight/**
            - Weight=group1, 8
          filters:
            - AddRequestParameter=routeId , {routeId}

        - id: weight_low
          uri: http://localhost:8080
          predicates:
            - Path=/weight/**
            - Weight=group1, 2
          filters:
            - AddRequestParameter=routeId , {routeId}
