spring:
  cloud:
    gateway:
      routes:
        - id: retry_route
          uri: https://example.org
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: INTERNAL_SERVER_ERROR
                methods: GET
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false

        - id: retryshortcut_route
          uri: https://example.org
          filters:
            - Retry=3,INTERNAL_SERVER_ERROR,GET,10ms,50ms,2,false